### PR TITLE
Window title bar color added for Sublime 3.

### PR DESCRIPTION
**Pull request by ozgrozer**
It would be awesome.

https://stackoverflow.com/a/45920805/1340552

### CODE REVIEW

**Comment by Code-DJ** [comment]
@ozgrozer this is cool.

I tried to match the foreground color as close to Atom as possible - "fg": [167, 175, 192].
Since we are using One Dark from Atom, should we match it with it?

I have mine customized by creating Packages/User/One Dark.sublime-theme and putting just the titlebar json in there. This matches Atom without the bottom border. It looks like currently there is no way to add a bottom border.

```
[
    {
        "class": "title_bar",
        "bg": [41, 45, 53],
        "fg": [167, 175, 192]
    }
]
```

**Comment by ozgrozer** [comment]
I've changed the foreground color. Now it looks better.

I think we can use my bg and your fg together :)

```json
[
    {
        "class": "title_bar",
        "bg": [33, 37, 43],
        "fg": [167, 175, 192]
    }
]
```

This is mine:


This is yours:

**Comment by andresmichel** [comment]
**I think it's time to update (Atom - One Dark) tabs.**

image

> 

What do you think?

**Comment by Code-DJ** [comment]
@ozgrozer Sounds good. Before replying to your PR, I had the same bg as yours :)

FYI - I think "bg": [41, 45, 53] doesn't look as good because we don't have the bottom border like Atom has. On the flip side having "bg": [33, 37, 43] results in the border of the sidebar (see the vertical black line) just hanging there without an end :)

sublime

**Comment by Code-DJ** [comment]
@andresmichel That looks much better. Just to be sure, did you only remove the top margin or did you also reduce the height of the tab? If you reduced the height, what impact does it have on the close buttons as those are 18x18 pngs?

Edit: Sorry - didn't see that you posted a screenshot of Atom, not an updated Sublime theme :)

**Comment by ozgrozer** [comment]
@Code-DJ I didn't notice that vertical black line until you say :) My screen brightness is very low. So what do you gonna do? :)

**Comment by andresmichel** [comment]
I'll make some changes to make it look as similar as possible, wait for the next update.

**Comment by Code-DJ** [comment]
Just got the updated package. Looks awesome. Thank you!

**Pull request closed without merging**
