### PR TITLE
docs(README): add recommended setting

### PR DESCRIPTION
**Pull request by kud**

### CODE REVIEW

**Comment by andresmichel** [comment]
The show_tab_close_buttons setting is true by default 🤔

**Comment by kud** [comment]
It's not about the fact it's by default, it's about explaining to people if they want to see the coloured point meaning it's unsaved, you *must* set this property to `true`. It's about doc, it's not about what's by default. :D

**Comment by andresmichel** [comment]
ok 👍

**Comment by kud** [comment]
Thank you @andresmichel ! ;)

**Pull request merged**
